# Python Data Types

- numeric
    - int
    - float
    - complex
- bool
- str
- list
- array
- tuple
- dictionary

## Numeric

In [819]:
value_1 = 5
value_2 = 3.3
value_3 = 5+3j #(x+yj) = (real number + imaginary number) i is replaced with j

print(f"The 1st value is {value_1} and the data type is {type(value_1)}")
print(f"The 2nd value is {value_2} and the data type is {type(value_2)}")
print(f"The 3rd value is {value_3} and the data type is {type(value_3)}")

The 1st value is 5 and the data type is <class 'int'>
The 2nd value is 3.3 and the data type is <class 'float'>
The 3rd value is (5+3j) and the data type is <class 'complex'>


In [820]:
import cmath

print("The real part of complex number is : ", end="")
print(value_3.real)

print("The imaginary part of complex number is : ", end="")
print(value_3.imag)

The real part of complex number is : 5.0
The imaginary part of complex number is : 3.0


## Bool

In [821]:
my_number = 10
guess = 10

if my_number == guess:
    print("correct")
else:
    print("Wrong")

correct


## Strings

In [822]:
A = 1
B = "1"
print(f"A is an {type(A)} and B is a {type(B)}.")

A is an <class 'int'> and B is a <class 'str'>.


In [823]:
print("Hello world")

Hello world


In [824]:
to = "world"
print(f"Hello {to}")

Hello world


In [825]:
name = "Claire"
print(name)

Claire


In [826]:
print(name.upper())

CLAIRE


In [827]:
print(name.lower())

claire


In [828]:
full_name = "      Kraft, Claire      "
full_name.strip()
print(f"My last name is:{full_name}.")

My last name is:      Kraft, Claire      .


In [829]:
full_name_proper= full_name.strip()
print(f"My last name is: {full_name_proper}.")

My last name is: Kraft, Claire.


In [830]:
last_name = full_name_proper.replace(", Claire", "")
last_name

'Kraft'

## List

In [831]:
colors = ["red", "yellow", "blue", "green"]
print(colors)
print(type(colors))

['red', 'yellow', 'blue', 'green']
<class 'list'>


In [832]:
print(colors[1])

yellow


In [833]:
print(colors[-1])

green


In [834]:
print(sorted(colors))

['blue', 'green', 'red', 'yellow']


In [835]:
print(sorted(colors, reverse=True))

['yellow', 'red', 'green', 'blue']


In [836]:
colors = ["red", "yellow", "blue", "green"]
removed = colors.pop(2)
print(f"{removed} was removed from the colors list.")
print(f"The reduced colors list look like this: {colors}")

blue was removed from the colors list.
The reduced colors list look like this: ['red', 'yellow', 'green']


In [837]:
colors = ["red", "yellow", "blue", "green"]
added = colors.append('purple')
print(colors)

['red', 'yellow', 'blue', 'green', 'purple']


## Array

simple one dim array

In [838]:
import array as arr
array_1 = arr.array("i", [1, 2, 3, 4, 5]) #i = all elements
print(array_1)
print(type(array_1))

array('i', [1, 2, 3, 4, 5])
<class 'array.array'>


In [839]:
import numpy as np
array_2 = np.array(["ranking", 1, 2, 3])
print (array_2)
print(type(array_2))

['ranking' '1' '2' '3']
<class 'numpy.ndarray'>


multi dim array

In [840]:
print("\n")
array_4 = np.array([[1,2,3,4], [5,6,7,8]])
print(array_4)
print(type(array_4))



[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [841]:
array_5 = np.array([[[1,2,3],[3,4,5]],
                [[6,7,8],[9,8,7]],
                [[6,5,4],[3,2,1]]])
print(array_5)

[[[1 2 3]
  [3 4 5]]

 [[6 7 8]
  [9 8 7]]

 [[6 5 4]
  [3 2 1]]]


do math operations on arrays

In [842]:
array = np.array([100, 25, 2])
half = array/5
print(half)
print(type(half))

[20.   5.   0.4]
<class 'numpy.ndarray'>


![list vs array](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZW4XjNiBNBHOe_pz7D7zl7R8Ll4h8BIeuIQ:https://soshace.com/wp-content/uploads/2019/10/Python-Array-Explained-and-Visualized-python-arrays-vs.-python-loops.png&usqp=CAU) 
source: https://soshace.com/python-array-explained-and-visualized/

![comparison table](https://media.geeksforgeeks.org/wp-content/uploads/20220525085238/Screenshot20220525085154.png) 
source: https://www.geeksforgeeks.org/linked-list-vs-array/

## Tuple

Features of

- can hold strings, ints, lists, etc
- immutable

### simple tuple

In [843]:
tuple1 = (9, "blue", 3.4)
print(tuple1)

(9, 'blue', 3.4)


In [844]:
tuple2 = (5, "red", 2.8)
print(tuple2)

(5, 'red', 2.8)


### concat

In [845]:
tuple3 = tuple1 + tuple2
print(tuple3)
print(type(tuple3))

(9, 'blue', 3.4, 5, 'red', 2.8)
<class 'tuple'>


### nested

In [846]:
nested_tuple = ("blue", [1,2,3], (4,5,6))
print(nested_tuple)

('blue', [1, 2, 3], (4, 5, 6))


### manipulate tuple

In [847]:
print(f"Removing the first element\n{nested_tuple[1:]}")

Removing the first element
([1, 2, 3], (4, 5, 6))


In [848]:
print(f"Reverse travel of the original nested tuple\n{nested_tuple[::-1]}")

Reverse travel of the original nested tuple
((4, 5, 6), [1, 2, 3], 'blue')


## Dictionary

kv

In [849]:
dunder_mifflin = {"Michael":"Manager", 
            "Pam":"Receptionist", 
            "Jim": "Salesman", 
            "Dwight": "Assistant to the Manager", 
            "Angela": "Accountant"
            }

dunder_mifflin

{'Michael': 'Manager',
 'Pam': 'Receptionist',
 'Jim': 'Salesman',
 'Dwight': 'Assistant to the Manager',
 'Angela': 'Accountant'}

multi kv

In [850]:
dunder_mifflin = [
    {"name": "Michael", "job": "Manger", "sex": "M"},
    {"name": "Pam", "job": "Receptionist", "sex": "F"},
    {"name": "Jim", "job": "Salesman", "sex": "M"},
    {"name": "Dwight", "job": "Assistant to the Manager", "sex": None},
    {"name": "Angela", "job": "Accountant", "sex": "F"}
    ]

print("\nPrints the keys and values in the dict based on selection")
for employee in dunder_mifflin:
    print(employee["name"], employee["job"], employee["sex"], sep=", ") # prints the keys and values


Prints the keys and values in the dict based on selection
Michael, Manger, M
Pam, Receptionist, F
Jim, Salesman, M
Dwight, Assistant to the Manager, None
Angela, Accountant, F
